version: '3.8'

services:

  agnft-auth_pg_db:
      image: postgres:14.1-alpine
      container_name: agnft_auth-db
      restart: always
      env_file:
        - ../environment/postgres.env
      ports:
        - '5432:5432'
      volumes:
        - ../app-data/pg:/var/lib/postgresql/data
      networks:
        - autogear-nft-service

  agnft-queue:
    image: rabbitmq:3.12.10-alpine
    container_name: agnft-queue
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ../app-data/rabbitmq:/var/lib/rabbitmq/
    networks:
        - autogear-nft-service


networks:
  autogear-nft-service:
